apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2
  labels:
    app: ms2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms2
  template:
    metadata:
      labels:
        app: ms2
    spec:
      containers:
      - name: ms2
        image: shuham12/ms2:1.0.0
        ports:
        - containerPort: 8090